{"timestamp":"2025-09-06T07:55:47.227313","level":"info","event":"DAG bundles loaded: dags-folder","logger":"airflow.dag_processing.bundles.manager.DagBundlesManager"}
{"timestamp":"2025-09-06T07:55:47.227915","level":"info","event":"Filling up the DagBag from /opt/airflow/dags/reddit_dag.py","logger":"airflow.models.dagbag.DagBag"}
{"timestamp":"2025-09-06T07:55:48.080854Z","level":"info","event":"DEBUG file_path from XCom: /opt/airflow/data/output/reddit_20250906.csv","chan":"stdout","logger":"task"}
{"timestamp":"2025-09-06T07:55:54.430639Z","level":"info","event":"Bucket already exists","chan":"stdout","logger":"task"}
{"timestamp":"2025-09-06T07:55:55.016649","level":"error","event":"Task failed with exception","logger":"task","error_detail":[{"exc_type":"PermissionError","exc_value":"Access Denied","exc_notes":[],"syntax_error":null,"is_cause":false,"frames":[{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/task_runner.py","lineno":825,"name":"run"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/task_runner.py","lineno":1088,"name":"_execute_task"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/bases/operator.py","lineno":408,"name":"wrapper"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/operators/python.py","lineno":212,"name":"execute"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/operators/python.py","lineno":235,"name":"execute_callable"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/callback_runner.py","lineno":81,"name":"run"},{"filename":"/opt/airflow/dags/pipelines/aws_s3_pipeline.py","lineno":16,"name":"upload_s3_pipeline"},{"filename":"/opt/airflow/dags/etls/aws_etl.py","lineno":31,"name":"upload_to_s3"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/fsspec/asyn.py","lineno":118,"name":"wrapper"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/fsspec/asyn.py","lineno":103,"name":"sync"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/fsspec/asyn.py","lineno":56,"name":"_runner"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/fsspec/asyn.py","lineno":565,"name":"_put"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/s3fs/core.py","lineno":1535,"name":"_isdir"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/s3fs/core.py","lineno":747,"name":"_lsdir"}]},{"exc_type":"ClientError","exc_value":"An error occurred (AccessDenied) when calling the ListObjectsV2 operation: Access Denied","exc_notes":[],"syntax_error":null,"is_cause":true,"frames":[{"filename":"/home/airflow/.local/lib/python3.12/site-packages/s3fs/core.py","lineno":734,"name":"_lsdir"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/s3fs/core.py","lineno":784,"name":"_iterdir"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/aiobotocore/paginate.py","lineno":30,"name":"__anext__"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/aiobotocore/client.py","lineno":412,"name":"_make_api_call"}]}]}
